import random
import time

from voice_output import speak_text


QUESTION_DB = {

    "frontend developer": [

    "What is HTML?",
    "What is CSS?",
    "What is JavaScript?",
    "What are React hooks?",
    "Explain useState hook.",
    "Explain useEffect hook.",
    "What is virtual DOM?",
    "Difference between props and state?",
    "What is responsive design?",
    "What is Flexbox?",
    "What is CSS Grid?",
    "What is Tailwind CSS?",
    "What is Bootstrap?",
    "Explain event bubbling.",
    "What is DOM manipulation?",
    "Difference between == and ===?",
    "What is asynchronous JavaScript?",
    "Explain promises in JavaScript.",
    "What is async await?",
    "What is API integration?",
    "Explain component lifecycle.",
    "What is Redux?",
    "What is React Router?",
    "What is lazy loading?",
    "Explain code splitting.",
    "What is local storage?",
    "What is session storage?",
    "Explain CORS.",
    "What is frontend optimization?",
    "How do you improve website performance?"
],


"backend developer": [

    "What is FastAPI?",
    "Explain REST API.",
    "What is JWT authentication?",
    "Difference between SQL and NoSQL?",
    "What is middleware?",
    "Explain CRUD operations.",
    "What is API security?",
    "What is asynchronous programming?",
    "Explain database indexing.",
    "What is caching?",
    "Explain microservices.",
    "What is Docker?",
    "Explain rate limiting.",
    "What is API gateway?",
    "Difference between PUT and PATCH?",
    "What is dependency injection?",
    "What is ORM?",
    "Explain SQL joins.",
    "What is normalization?",
    "What is database schema?",
    "Explain server-side rendering.",
    "What is load balancing?",
    "What is scalability?",
    "What is WebSocket?",
    "Explain authentication vs authorization.",
    "What is hashing?",
    "What is encryption?",
    "Explain MVC architecture.",
    "What is multithreading?",
    "Explain message queues."
],


"full stack developer": [

    "What is MERN stack?",
    "Explain React.",
    "What is Node.js?",
    "What is Express.js?",
    "What is MongoDB?",
    "What is API integration?",
    "Explain frontend and backend communication.",
    "What is JWT authentication?",
    "What is Redux?",
    "What is responsive design?",
    "What is REST API?",
    "Explain CRUD operations.",
    "What is middleware?",
    "What is Docker?",
    "What is deployment?",
    "Explain Git workflow.",
    "What is cloud hosting?",
    "What is session management?",
    "Difference between SQL and NoSQL?",
    "Explain virtual DOM.",
    "What is asynchronous programming?",
    "Explain API security.",
    "What is CI/CD?",
    "What is scalability?",
    "What is load balancing?",
    "What is caching?",
    "Explain authentication flow.",
    "What is component lifecycle?",
    "What is database indexing?",
    "How do you optimize full stack applications?"
],


"python developer": [

    "What is Python?",
    "Explain decorators.",
    "What are generators?",
    "What is list comprehension?",
    "What is lambda function?",
    "Explain OOP in Python.",
    "What is inheritance?",
    "What is polymorphism?",
    "What is encapsulation?",
    "What is abstraction?",
    "What is FastAPI?",
    "What is Flask?",
    "What is Django?",
    "What is virtual environment?",
    "What is pip?",
    "Explain multithreading.",
    "What is GIL in Python?",
    "Explain exception handling.",
    "What is file handling?",
    "What is JSON?",
    "Explain REST API.",
    "What is ORM?",
    "Difference between tuple and list?",
    "What is Python packaging?",
    "What is recursion?",
    "What is asynchronous programming?",
    "Explain API development.",
    "What is unit testing?",
    "Explain Python modules.",
    "How do you optimize Python code?"
],


"java developer": [

    "What is JVM?",
    "What is JDK?",
    "What is JRE?",
    "Explain OOP concepts.",
    "What is inheritance?",
    "What is polymorphism?",
    "What is abstraction?",
    "What is encapsulation?",
    "Explain multithreading.",
    "What is synchronization?",
    "What is Spring Boot?",
    "What is Hibernate?",
    "What is JDBC?",
    "Explain collections framework.",
    "What is exception handling?",
    "What is garbage collection?",
    "What is REST API?",
    "What is Maven?",
    "What is dependency injection?",
    "What is microservices architecture?",
    "What is interface in Java?",
    "Difference between abstract class and interface?",
    "What is lambda expression?",
    "What is stream API?",
    "Explain Java memory management.",
    "What is serialization?",
    "What is constructor overloading?",
    "What is method overriding?",
    "What is API security?",
    "How do you optimize Java applications?"
],


"data analyst": [

    "What is data analysis?",
    "Explain SQL joins.",
    "What is Excel?",
    "What is Power BI?",
    "What is Tableau?",
    "What is ETL?",
    "What is data cleaning?",
    "What is data visualization?",
    "Explain pivot tables.",
    "What is normalization?",
    "What is KPI?",
    "Explain dashboards.",
    "What is data preprocessing?",
    "What is business intelligence?",
    "What is Python Pandas?",
    "Explain NumPy.",
    "What is data wrangling?",
    "What is regression analysis?",
    "Explain descriptive statistics.",
    "What is hypothesis testing?",
    "What is correlation?",
    "What is data storytelling?",
    "What is data mining?",
    "Explain SQL aggregation.",
    "What is filtering in SQL?",
    "What is trend analysis?",
    "What is forecasting?",
    "What is exploratory data analysis?",
    "What is data governance?",
    "How do you create business reports?"
],


"data scientist": [

    "What is data science?",
    "What is machine learning?",
    "Explain supervised learning.",
    "Explain unsupervised learning.",
    "What is overfitting?",
    "What is underfitting?",
    "Explain bias vs variance.",
    "What is regression?",
    "What is classification?",
    "What is clustering?",
    "What is feature engineering?",
    "What is feature scaling?",
    "What is cross validation?",
    "Explain decision trees.",
    "What is random forest?",
    "What is logistic regression?",
    "What is deep learning?",
    "What is NLP?",
    "Explain neural networks.",
    "What is gradient descent?",
    "What is Pandas?",
    "What is NumPy?",
    "What is Matplotlib?",
    "What is Seaborn?",
    "Explain data preprocessing.",
    "What is model evaluation?",
    "What is precision and recall?",
    "What is confusion matrix?",
    "What is hyperparameter tuning?",
    "How do you deploy ML models?"
],


"ai ml engineer": [

    "What is machine learning?",
    "What is deep learning?",
    "Explain neural networks.",
    "What is TensorFlow?",
    "What is PyTorch?",
    "What is CNN?",
    "What is RNN?",
    "What is transformer architecture?",
    "What is NLP?",
    "What is computer vision?",
    "Explain supervised learning.",
    "What is unsupervised learning?",
    "What is reinforcement learning?",
    "What is overfitting?",
    "What is underfitting?",
    "Explain gradient descent.",
    "What is backpropagation?",
    "What is feature engineering?",
    "What is transfer learning?",
    "What is model deployment?",
    "What is MLOps?",
    "What is hyperparameter tuning?",
    "What is data preprocessing?",
    "Explain confusion matrix.",
    "What is precision and recall?",
    "What is OpenCV?",
    "What is Hugging Face?",
    "What is LLM?",
    "Explain AI ethics.",
    "How do you optimize ML models?"
],


"software engineer": [

    "What is OOP?",
    "Explain data structures.",
    "What is linked list?",
    "What is stack?",
    "What is queue?",
    "Explain recursion.",
    "What is binary search?",
    "What is sorting algorithm?",
    "What is time complexity?",
    "What is space complexity?",
    "Explain arrays.",
    "What is hashing?",
    "What is database indexing?",
    "What is API?",
    "What is Git?",
    "What is SDLC?",
    "What is Agile methodology?",
    "What is debugging?",
    "What is multithreading?",
    "What is operating system?",
    "What is networking?",
    "What is cloud computing?",
    "What is Docker?",
    "What is CI/CD?",
    "Explain microservices.",
    "What is software testing?",
    "What is unit testing?",
    "What is system design?",
    "What is scalability?",
    "How do you optimize software applications?"
],

"devops engineer": [

    "What is DevOps?",
    "What is Docker?",
    "What is Kubernetes?",
    "Explain CI/CD.",
    "What is Jenkins?",
    "What is GitHub Actions?",
    "What is Infrastructure as Code?",
    "What is Terraform?",
    "What is Ansible?",
    "What is monitoring?",
    "What is logging?",
    "What is AWS?",
    "What is Azure?",
    "What is load balancing?",
    "What is containerization?",
    "What is virtualization?",
    "Explain deployment pipeline.",
    "What is scalability?",
    "What is Linux?",
    "What is shell scripting?",
    "What is version control?",
    "What is Nginx?",
    "What is reverse proxy?",
    "What is cloud automation?",
    "What is Kubernetes pod?",
    "What is Helm?",
    "What is serverless architecture?",
    "What is blue green deployment?",
    "What is rolling deployment?",
    "How do you ensure system reliability?"
],


"cyber security engineer": [

    "What is cyber security?",
    "What is ethical hacking?",
    "What is SQL injection?",
    "Explain XSS attack.",
    "What is phishing?",
    "What is malware?",
    "What is ransomware?",
    "What is firewall?",
    "What is VPN?",
    "What is penetration testing?",
    "What is encryption?",
    "What is hashing?",
    "Difference between HTTP and HTTPS?",
    "What is authentication?",
    "What is authorization?",
    "What is multi factor authentication?",
    "What is OWASP?",
    "Explain brute force attack.",
    "What is network security?",
    "What is IDS and IPS?",
    "What is social engineering?",
    "What is packet sniffing?",
    "What is zero day attack?",
    "What is DNS spoofing?",
    "What is cyber forensics?",
    "What is vulnerability assessment?",
    "Explain SSL certificates.",
    "What is risk management?",
    "What is data breach?",
    "How do you secure web applications?"
],


"cloud engineer": [

    "What is cloud computing?",
    "What is AWS?",
    "What is Azure?",
    "What is Google Cloud?",
    "What is EC2?",
    "What is S3 bucket?",
    "What is load balancing?",
    "What is autoscaling?",
    "What is serverless computing?",
    "What is virtualization?",
    "What is Docker?",
    "What is Kubernetes?",
    "What is cloud security?",
    "What is cloud deployment model?",
    "Difference between IaaS and PaaS?",
    "What is SaaS?",
    "What is VPC?",
    "What is CDN?",
    "What is cloud storage?",
    "What is disaster recovery?",
    "What is Terraform?",
    "What is Infrastructure as Code?",
    "What is cloud monitoring?",
    "What is cloud migration?",
    "What is DNS?",
    "What is CI/CD?",
    "What is API gateway?",
    "What is hybrid cloud?",
    "What is multi cloud?",
    "How do you optimize cloud costs?"
],


"mobile app developer": [

    "What is Android development?",
    "What is iOS development?",
    "What is Flutter?",
    "What is React Native?",
    "What is Kotlin?",
    "What is Swift?",
    "What is APK?",
    "What is responsive mobile design?",
    "What is mobile app lifecycle?",
    "What is API integration?",
    "What is Firebase?",
    "What is SQLite?",
    "What is state management?",
    "What is navigation in Flutter?",
    "What is widget in Flutter?",
    "What is emulator?",
    "What is push notification?",
    "What is app deployment?",
    "What is Play Store publishing?",
    "What is App Store publishing?",
    "What is REST API?",
    "What is local storage?",
    "What is asynchronous programming?",
    "What is debugging?",
    "What is performance optimization?",
    "What is cross platform development?",
    "What is mobile testing?",
    "What is authentication?",
    "What is deep linking?",
    "How do you improve app performance?"
],


"qa engineer": [

    "What is software testing?",
    "What is QA?",
    "Difference between QA and QC?",
    "What is unit testing?",
    "What is integration testing?",
    "What is system testing?",
    "What is regression testing?",
    "What is automation testing?",
    "What is Selenium?",
    "What is test case?",
    "What is test plan?",
    "What is bug life cycle?",
    "What is smoke testing?",
    "What is sanity testing?",
    "What is load testing?",
    "What is stress testing?",
    "What is performance testing?",
    "What is API testing?",
    "What is JUnit?",
    "What is TestNG?",
    "What is black box testing?",
    "What is white box testing?",
    "What is user acceptance testing?",
    "What is defect tracking?",
    "What is Jenkins?",
    "What is CI/CD testing?",
    "What is manual testing?",
    "What is automation framework?",
    "What is agile testing?",
    "How do you ensure software quality?"
],


"blockchain developer": [

    "What is blockchain?",
    "What is cryptocurrency?",
    "What is Bitcoin?",
    "What is Ethereum?",
    "What is smart contract?",
    "What is Solidity?",
    "What is Web3?",
    "What is decentralization?",
    "What is mining?",
    "What is proof of work?",
    "What is proof of stake?",
    "What is NFT?",
    "What is gas fee?",
    "What is MetaMask?",
    "What is consensus algorithm?",
    "What is distributed ledger?",
    "What is hashing in blockchain?",
    "What is private blockchain?",
    "What is public blockchain?",
    "What is DAO?",
    "What is tokenization?",
    "What is crypto wallet?",
    "What is blockchain security?",
    "What is Ethereum Virtual Machine?",
    "What is smart contract deployment?",
    "What is blockchain scalability?",
    "What is layer 2 solution?",
    "What is IPFS?",
    "What is dApp?",
    "How do you secure blockchain applications?"
],


"ui ux designer": [

    "What is UI design?",
    "What is UX design?",
    "Difference between UI and UX?",
    "What is wireframe?",
    "What is prototype?",
    "What is Figma?",
    "What is Adobe XD?",
    "What is user research?",
    "What is usability testing?",
    "What is responsive design?",
    "What is typography?",
    "What is color theory?",
    "What is design thinking?",
    "What is accessibility?",
    "What is user journey?",
    "What is information architecture?",
    "What is visual hierarchy?",
    "What is interaction design?",
    "What is low fidelity prototype?",
    "What is high fidelity prototype?",
    "What is heuristic evaluation?",
    "What is mobile first design?",
    "What is design system?",
    "What is consistency in UI?",
    "What is white space?",
    "What is micro interaction?",
    "What is persona creation?",
    "What is A/B testing?",
    "What is user centered design?",
    "How do you improve user experience?"
],


"game designer": [

    "What is game design?",
    "What is Unity?",
    "What is Unreal Engine?",
    "What is game mechanics?",
    "What is level design?",
    "What is character design?",
    "What is game loop?",
    "What is FPS game?",
    "What is RPG game?",
    "What is multiplayer game?",
    "What is physics engine?",
    "What is animation in games?",
    "What is collision detection?",
    "What is game balancing?",
    "What is AI in games?",
    "What is 2D game development?",
    "What is 3D game development?",
    "What is shader in gaming?",
    "What is rendering?",
    "What is game optimization?",
    "What is storytelling in games?",
    "What is sound design?",
    "What is texture mapping?",
    "What is NPC?",
    "What is game testing?",
    "What is procedural generation?",
    "What is AR gaming?",
    "What is VR gaming?",
    "What is monetization in games?",
    "How do you improve player experience?"
],


"embedded systems engineer": [

    "What is embedded system?",
    "What is microcontroller?",
    "What is Arduino?",
    "What is Raspberry Pi?",
    "What is IoT?",
    "What is real time operating system?",
    "What is firmware?",
    "What is serial communication?",
    "What is SPI protocol?",
    "What is I2C protocol?",
    "What is UART?",
    "What is interrupt?",
    "What is sensor interfacing?",
    "What is actuator?",
    "What is PCB?",
    "What is embedded C?",
    "What is memory management?",
    "What is bootloader?",
    "What is GPIO?",
    "What is watchdog timer?",
    "What is ADC?",
    "What is PWM?",
    "What is edge computing?",
    "What is power optimization?",
    "What is debugging in embedded systems?",
    "What is RTOS scheduling?",
    "What is CAN protocol?",
    "What is Bluetooth Low Energy?",
    "What is hardware software integration?",
    "How do you optimize embedded systems?"
]
}



def generate_questions(role):

    role = role.lower()

    questions = QUESTION_DB.get(role, [])

    selected_questions = random.sample(

        questions,

        min(5, len(questions))
    )
    random.shuffle(selected_questions)
    return selected_questions